import = ["/home/jesse/.config/alacritty/themes/hyper.toml", "/home/jesse/.config/alacritty/keybindings.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[shell]
program = "fish"

[window]
dynamic_padding = false
opacity = 0.85
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 130
lines = 32

[window.padding]
x = 6
y = 6

[window.position]
x = 0
y = 0
